# Generated by Django 3.1.4 on 2021-01-19 05:55

import app.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import webpush.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', models.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', models.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='Welcome Notification', max_length=200)),
                ('message', models.CharField(default='A Notification is sent to the subscriber as soon as they subscribe to your store notification', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_reminders', app.fields.JSONSchemaField(default=list)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', models.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', models.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='Shipping Notification', max_length=200)),
                ('message', models.CharField(default='Get notified for the shipments you will be delivering', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_reminders', app.fields.JSONSchemaField(default=list)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', models.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', models.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='PriceDrop Notification', max_length=200)),
                ('message', models.CharField(default='Get notifications, as soon as there is slight change in product price', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_reminders', app.fields.JSONSchemaField(default=list)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', models.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', models.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='BackInStock Notification', max_length=200)),
                ('message', models.CharField(default='Black Friday 30% OFF on all Products', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_reminders', app.fields.JSONSchemaField(default=list)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', models.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', models.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='Abandoned Cart Notification', max_length=200)),
                ('message', models.CharField(default='Claim revenue from shoppers, who left their items in cart', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('extra_reminders', app.fields.JSONSchemaField(default=list)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
