# Generated by Django 3.1.4 on 2021-01-19 05:55

import app.fields
from django.db import migrations, models
import django.db.models.deletion
import subscribes.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('self_unsubscribed', models.BooleanField(default=False)),
                ('is_test_device', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_data', models.JSONField(default={})),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=20, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system_version', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=300, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('subscription_info', models.JSONField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('segment_key', models.CharField(default=subscribes.utils.generate_segment_key, max_length=25)),
                ('groups', app.fields.JSONSchemaField(default=[])),
                ('audience_reach', models.IntegerField(default=-1)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
