# Generated by Django 3.1.4 on 2021-01-03 17:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import webpush.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subscribes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', django.contrib.postgres.fields.jsonb.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', django.contrib.postgres.fields.jsonb.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Discarded', 'Discarded')], default='Waiting', max_length=15)),
                ('campaign_category', models.CharField(choices=[('Regular', 'Regular'), ('Flash_Sale', 'Flash_Sale')], default='Regular', max_length=15)),
                ('auth', models.TextField(blank=True, null=True)),
                ('immediately', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('total_subs', models.IntegerField(default=0)),
                ('sent_subs', models.IntegerField(default=0)),
                ('segments', models.ManyToManyField(blank=True, to='Subscribes.Segment')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
