# Generated by Django 3.1.4 on 2021-01-04 07:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pushNotifications.fields
import webpush.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePlaybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
                ('landing_url', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_time', models.IntegerField(default=webpush.helpers.get_default_expiry_time)),
                ('sticky', models.BooleanField(default=True)),
                ('utm_params', django.contrib.postgres.fields.jsonb.JSONField(default=webpush.helpers.get_campaign_default_utm_params)),
                ('ctas', django.contrib.postgres.fields.jsonb.JSONField(default=webpush.helpers.get_campaign_default_ctas)),
                ('mobile_homepage', models.BooleanField(default=False)),
                ('desktop_homepage', models.BooleanField(default=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enabled', models.BooleanField(default=True)),
                ('welcome_push_enabled', models.BooleanField(default=True)),
                ('extra_reminders', pushNotifications.fields.JSONSchemaField(default=list)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
